spring.application.name=productpulse
spring.datasource.url=jdbc:mysql://localhost:3306/productpulse
spring.datasource.username=root
spring.datasource.password=June#12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=mGxKvXWnUlPmcXq7rq7ab73bdLGZdGZ1YNBrSAOB+Ls=

